companieshouse/admin.orders.web.ch.gov.uk

routes.yaml
* Create the basic yaml file with the required weight and routes
=> GCI-2059 Add routes.yaml for admin.orders.web.ch.gov.uk service

cucumber.js, features/say_hello.feature, features/support/core/BrowserAgent.ts, features/support/core/Harness.ts, features/support/core/SeleniumBrowserAgent.ts, features/support/hello/GreetingPage.ts, features/support/hello/GreetingSteps.ts, package-lock.json, package.json, src/application/Application.ts, src/application/Config.ts, src/application/Registrar.ts, src/hello/GoodbyeController.ts, src/hello/HelloController.ts, src/views/hello/goodbye.njk, src/views/hello/hello.njk, tsconfig.json
* Integration test framework implemented using Cucumber JS and Selenium.
* Feature files and support classes located underneath features/.
* Accept "0" as a valid port mapping; this will cause Node to start an
HTTP server on a random port.
* Expose port number from Application class.
* Integration tests run via npm run test-integration.
=> GCI-2056 Implement BDD int test framework

features/support/core/BrowserAgent.ts, features/support/core/Harness.ts, features/support/core/SeleniumBrowserAgent.ts, features/support/core/ZombieBrowserAgent.ts, features/support/hello/GreetingSteps.ts, package-lock.json, package.json
* The ZombieJS agent will be used to run BDD tests against a
self-contained headless browser.
* The Selenium agent will be used to run BDD tests against Chrome.
=> GCI-2054 Implement ZombieJS agent

Dockerfile, Makefile, src/application/ServerPaths.ts, start.sh
* Fix errors caused by incorrect production mode path.
=> Fix production mode paths

routes.yaml
* Resolves routing conflict between 
orders.web.ch.gov.uk and admin.orders.web.ch.gov.uk.
=> Increase priority of orders-admin route

features/support/core/SeleniumBrowserAgent.ts, features/support/core/ZombieBrowserAgent.ts, src/search/FakeSearchService.ts
* Text input implemented for SeleniumBrowserAgent via `sendKeys`.
* Fixed bug in ZombieBrowserAgent whereby form wouldn't be submitted if
click method used on submit button.
=> Add text input support to SeleniumBrowserAgent

src/core/ErrorPageBuildable.ts, src/core/GlobalPageFactory.ts, src/core/UnauthorisedComponent.ts, src/search/PageFactory.ts, src/security/AuthenticationMiddleware.ts, src/security/AuthorisationMiddleware.ts, src/security/RedisSessionMiddleware.ts, src/session/OrderAdminSession.ts, src/session/SessionModel.ts, src/views/unauthorised.njk, test/core/GlobalPageFactory.test.ts, test/search/PageFactory.test.ts, test/security/AuthenticationMiddleware.test.ts, test/security/AuthorisationMiddleware.test.ts, test/session/SessionModel.test.ts
* Authorisation middleware checks the signed in user's permissions. If
the user has permission /admin/chs-order-investigation then the user
is allowed to proceed. Otherwise, "Unauthorised" rendered.
* Encapsulate interactions with session required by authentication and
authorisation middleware in SessionModel object.
=> GCI-2092 Implement authorisation and refine session

features/orders_search_page.feature, features/support/core/BrowserAgent.ts, features/support/core/SeleniumBrowserAgent.ts, features/support/core/ZombieBrowserAgent.ts, features/support/search/SearchPage.ts, features/support/search/SearchSteps.ts, src/application/Registrar.ts, src/public/stylesheets/app.scss, src/views/logout.njk, src/views/page.njk
* Upon clicking sign out, user will be returned to the sign in page.
=> GCI-2098 Implement sign out button

package-lock.json, package.json, src/orderdetails/CertificateTextMapper.ts, src/orderdetails/DefaultOrderDetailsMapper.ts, src/orderdetails/OrderDetails.ts, src/views/orderDetails/delivery_details_component.njk, test/orderdetails/DefaultOrderDetailsMapper.test.ts
=> BI-11245 - Update same-day delivery text and add email copy required section 

package-lock.json, src/govuk/GovUkSummaryList.ts, src/mappers/MapperRequest.ts, src/orderitemsummary/GovUkOrderItemSummaryView.ts, src/orderitemsummary/OrderItemMapper.ts, src/orderitemsummary/OrderItemRequest.ts, src/orderitemsummary/OrderItemSummaryController.ts, src/orderitemsummary/OrderItemSummaryFactory.ts, src/orderitemsummary/OrderItemSummaryService.ts, src/orderitemsummary/OrderItemView.ts
* Declare skeleton classes for order item summary pages
[GCI-2304](https://companieshouse.atlassian.net/browse/GCI-2304)
=> GCI-2304 Declare skeleton classes for order item summary pages

package-lock.json, package.json, src/orderitemsummary/FilingHistoryMapper.ts, src/orderitemsummary/MissingImageDeliveryDetailsComponent.ts, src/orderitemsummary/MissingImageDeliveryMapper.ts, src/orderitemsummary/MissingImageDeliverySummary.ts, src/orderitemsummary/MissingImageItemSummaryPage.ts, src/orderitemsummary/NullOrderItemMapper.ts, src/orderitemsummary/OrderItemMapper.ts, src/orderitemsummary/OrderItemRequest.ts, src/orderitemsummary/OrderItemSummaryController.ts, src/orderitemsummary/OrderItemSummaryFactory.ts, src/orderitemsummary/OrderItemSummaryService.ts, src/orderitemsummary/OrderItemView.ts, test/__mocks__/mocks.ts, test/__mocks__/order.mocks.ts, test/orderitemsummary/MissingImageDeliveryMapper.unit.test.ts, test/orderitemsummary/OrderItemSummaryFactory.unit.test.ts, test/orderitemsummary/OrderItemSummaryService.test.ts
* Implement item summary service 
* Returns mapped item when HTTP success code
* Returns client error when HTTP 404 returned by api
* Returns server error when any other HTTP error code
[GCI-2306](https://companieshouse.atlassian.net/browse/GCI-2306)
=> GCI-2306 Implement item summary service

src/application/Registrar.ts, src/orderitemsummary/OrderItemSummaryController.ts, test/orderitemsummary/OrderItemSummaryController.test.ts
* OrderItemSummaryController responsible for fetching and rendering an order item from provided order ID and item ID.
=> GCI-2305 Implement OrderItemSummaryController

.dockerignore, Dockerfile, package.json, src/mappers/FilingHistoryMapper.ts, src/orderitemsummary/MissingImageDeliveryMapper.ts, src/orderitemsummary/OrderItemSummaryFactory.ts, test/mappers/FilingHistoryMapper.test.ts, test/orderitemsummary/MissingImageDeliveryMapper.unit.test.ts, test/orderitemsummary/OrderItemSummaryFactory.unit.test.ts, test/orderitemsummary/OrderItemSummaryService.test.ts
* Refactor FilingHistoryMapper as class to allow api-enumerations to be loaded via ServerPaths.
=> Fix issue with api-enumerations loading

src/views/orderItemSummary/order_item_summary_mid.njk
* Implement mid item summary template
[GCI-2307](https://companieshouse.atlassian.net/browse/GCI-2307)
=> GCI-2307 Implement mid item summary template

Makefile
* Fixes issue with folder structure causing deployments >= 0.1.29 to fail.
=> Fix issue in Makefile breaking folder structure

src/views/orderItemSummary/order_item_summary_ccd.njk
* Implement ccd template
[GCI-2313](https://companieshouse.atlassian.net/browse/GCI-2313)
=> GCI-2313 Implement ccd template

src/order_summary/OrderSummary.ts, src/order_summary/OrderSummaryConverter.ts, src/views/orderSummary/item_details.njk, test/order_summary/OrderSummaryService.unit.test.ts
* OrderSummaryConverter now generates links for each item to order item summary page.
=> Fix item links on order summary page

package-lock.json, src/views/orderItemSummary/order_item_summary_mid.njk
* Change div class to govuk-grid-column-two-thirds
* Add missing closing angle brackets and quotes
[GCI-2307](https://companieshouse.atlassian.net/browse/GCI-2307)
=> GCI-2307 Fix html errors in order item summary mid

src/orderitemsummary/CertifiedCopyDocumentDetailsComponent.ts, src/orderitemsummary/CertifiedCopyItemDetailsComponent.ts, src/orderitemsummary/CertifiedCopyMapper.ts, src/views/orderItemSummary/certified_copy_document_details_component.njk, src/views/orderItemSummary/certified_copy_item_details_component.njk
* Separates item details and document details into different components for certified copies
[GCI-2323](https://companieshouse.atlassian.net/browse/GCI-2323)
=> GCI-2323 Move document details to separate component

package-lock.json, test/__mocks__/mocks.ts, test/orderitemsummary/OrderItemSummaryController.test.ts, test/orderitemsummary/OrderItemSummaryService.test.ts
* Fix expected view models for copies
* Change dist imports in unit tests to use src
=> GCI-2323 Fix failing unit tests

src/views/orderItemSummary/order_item_summary_certificate.njk
* Convert newlines to br tag in certificate order item summary template.
* Fixes automation test failures when run with SeleniumBrowserAgent.
* Also fixes layout issues with directors/secretaries/members details.
=> Fix automation test failures

Tiltfile.dev, features/order_summary_page.feature, src/order_summary/OrderSummary.ts, src/order_summary/OrderSummaryConverter.ts, src/views/orderSummary/payment_details.njk, test/order_summary/OrderSummaryService.unit.test.ts
- Add Tiltfile.dev to enable development mode in tilt
- Update order summary page to include payment status
- Update unit and cucumber tests
Resolves: BI-11877
=> BI-11877 - Add payment status to admin order summary page

.dockerignore, Dockerfile, Makefile, routes.yaml
Removes redundant files and their references after v18 migration
=> Chore: Remove redundant files and their references

Dockerfile
=> Feat/CC-1117: Bump docker image to v20

README.md, package.json, src/application/Application.ts, terraform/groups/ecs-service/locals.tf
Adding Health check to the service
=> Draft : Adding Health Check and Terraform update 

cucumber.js, features/support/core/Harness.ts, package-lock.json, package.json, src/application/Application.ts, src/application/NunjucksConfigurator.ts, src/config/EnvironmentProperties.ts, src/security/CsrfMiddleware.ts, src/security/MiddlewareProvider.ts, src/security/RedisSessionMiddleware.ts, src/views/csrf_token.njk, src/views/page.njk, src/views/search/multi/search_component.njk, src/views/search/search_component.njk, test/__mocks__/csrf.mocks.ts, test/config/TestEnvironmentProperties.ts, test/order_summary/OrderSummaryController.test.ts, test/orderdetails/OrderDetailsController.test.ts, test/orderitemsummary/OrderItemSummaryController.test.ts, test/search/SearchController.test.ts
Resolves SEC-69/SEC-70/SEC-71
Changes include:
- Upgraded to use latest web security node
- Package upgrades / additions as needed
- Middleware setup
- Creation of csrf_token.njk to represent CRSF token 
- Token added to search components
- CSRF error handling added
- Tests updates
=> SEC-69/SEC-70/SEC-71 - CSRF upgrade changes for admin orders web
